"""Local source-ingestion helpers.

The modules in this package preserve source structure and provenance. They do
not decide code applicability or compliance.
"""

from .ibc2018 import (
    CHAPTER_SPECS,
    LAYOUT_ANALYSIS_VERSION,
    SEED_VERSION,
    ChapterLayout,
    ChapterLayoutAnalysis,
    ChapterSeed,
    ChapterSpec,
    IbcLayoutDocument,
    LogicalBlock,
    build_chapter_seed,
    coalesce_visual_lines,
    extract_ibc2018_layout,
    merge_visual_fragments,
    order_page_lines,
    parse_chapter_numbers,
    reconstruct_glyph_line,
)
from .layout_analysis import (
    BodyFontProfile,
    CleanedPage,
    PageLines,
    PageOrderProfile,
    ReadingOrderMode,
    RecurringMargins,
    RemovedLine,
    RuleSegment,
    SourceFragment,
    VisualLine,
    clean_recurring_margins,
    detect_recurring_margins,
    estimate_body_font,
    infer_page_order,
    order_page_lines as order_analyzed_page_lines,
    structural_margin_key,
    visual_line_id,
)
from .layout_validation import (
    validate_layout_projection,
    validate_line_coverage,
    validate_page_profiles,
    validate_table_candidate,
)
from .nec2017 import (
    ArticleRange,
    ArticleSeed,
    SourceManifest,
    SourceMapEntry,
    build_article_seed,
    discover_article_ranges,
    select_article_blocks,
)
from .pdf_layout import (
    PdfBlock,
    PdfLayoutDocument,
    PdfOutlineItem,
    PdfPage,
    extract_pdf_layout,
    normalize_block_text,
    order_content_blocks,
)
from .table_geometry import (
    TableCandidate,
    TableCellCandidate,
    TableRowCandidate,
    detect_ruled_tables,
    detect_table_rows,
    group_table_candidates,
)

__all__ = [
    "ArticleRange",
    "ArticleSeed",
    "BodyFontProfile",
    "CHAPTER_SPECS",
    "ChapterLayout",
    "ChapterLayoutAnalysis",
    "ChapterSeed",
    "ChapterSpec",
    "CleanedPage",
    "IbcLayoutDocument",
    "LAYOUT_ANALYSIS_VERSION",
    "LogicalBlock",
    "PageLines",
    "PageOrderProfile",
    "PdfBlock",
    "PdfLayoutDocument",
    "PdfOutlineItem",
    "PdfPage",
    "ReadingOrderMode",
    "RecurringMargins",
    "RemovedLine",
    "RuleSegment",
    "SEED_VERSION",
    "SourceFragment",
    "SourceManifest",
    "SourceMapEntry",
    "TableCandidate",
    "TableCellCandidate",
    "TableRowCandidate",
    "VisualLine",
    "build_article_seed",
    "build_chapter_seed",
    "clean_recurring_margins",
    "coalesce_visual_lines",
    "detect_recurring_margins",
    "detect_ruled_tables",
    "detect_table_rows",
    "discover_article_ranges",
    "estimate_body_font",
    "extract_ibc2018_layout",
    "extract_pdf_layout",
    "group_table_candidates",
    "infer_page_order",
    "merge_visual_fragments",
    "normalize_block_text",
    "order_analyzed_page_lines",
    "order_content_blocks",
    "order_page_lines",
    "parse_chapter_numbers",
    "reconstruct_glyph_line",
    "select_article_blocks",
    "structural_margin_key",
    "validate_layout_projection",
    "validate_line_coverage",
    "validate_page_profiles",
    "validate_table_candidate",
    "visual_line_id",
]
