"""Public source-evidence contracts."""

from . import amendments as _amendments
from .adapters import (
    AdapterResult,
    EvidenceAdapter,
    EvidenceDiagnostic,
    SourceRegion,
    run_evidence_adapter,
)
from .amendments import (
    AMENDMENT_OPERATION_VALUES,
    AMENDMENT_PATCH_VERSION,
    AmendmentOperation,
    AmendmentSet,
    JurisdictionalAmendmentPatch,
    NormalizedWashingtonWacHtmlAdapter,
    amendment_patch_from_dict,
)
from .development import (
    DEVELOPMENT_DISPOSITION_VALUES,
    DEVELOPMENT_KIND_VALUES,
    DEVELOPMENT_RECORD_VERSION,
    DevelopmentDisposition,
    DevelopmentLineage,
    DevelopmentRecord,
    DevelopmentRecordKind,
    IccDevelopmentTextAdapter,
    development_record_from_dict,
)
from .errata import (
    ERRATA_RECORD_VERSION,
    ERRATUM_OPERATION_VALUES,
    TARGET_KIND_VALUES,
    ErratumOperation,
    ErratumRecord,
    IccErrataPdfAdapter,
    TargetKind,
    erratum_record_from_dict,
)
from .icc_action_report import IccCommitteeActionReportPdfAdapter
from .icc_development import IccActionStage, IccProposalMonographPdfAdapter
from .io import source_register_from_dict
from .model import (
    ACCESS_SCOPE_VALUES,
    EVIDENCE_ROLE_VALUES,
    RIGHTS_STATUS_VALUES,
    SOURCE_REGISTER_VERSION,
    AccessScope,
    AstSourceIdentity,
    EvidenceRole,
    PublicationIdentity,
    RightsStatus,
    SourceRegister,
    SourceRegisterEntry,
    publication_state_id,
)
from .source_object_hydration import (
    SOURCE_OBJECT_HYDRATION_RECEIPT_VERSION,
    HydrationStatus,
    SourceObjectFetcher,
    SourceObjectHydrationReceipt,
    hydrate_source_object,
    validate_source_object_requirement,
    verify_local_source_object,
)
from .source_objects import (
    PRIVATE_SOURCE_OBJECT_LOCATOR_VERSION,
    SOURCE_OBJECT_CATALOG_VERSION,
    ObjectProvider,
    PrivateSourceObjectLocator,
    PrivateSourceObjectLocatorRegistry,
    SourceObjectCatalog,
    SourceObjectRequirement,
    private_source_object_locator_registry_from_dict,
    source_object_catalog_from_dict,
    validate_source_object_catalog,
)
from .washington_official import (
    WashingtonOfficialWacHtmlAdapter,
    WashingtonWacHtmlAdapter,
)

IccCommitteeActionPdfAdapter = IccCommitteeActionReportPdfAdapter
_amendments.WashingtonWacHtmlAdapter = WashingtonWacHtmlAdapter

__all__ = [
    "ACCESS_SCOPE_VALUES",
    "AMENDMENT_OPERATION_VALUES",
    "AMENDMENT_PATCH_VERSION",
    "DEVELOPMENT_DISPOSITION_VALUES",
    "DEVELOPMENT_KIND_VALUES",
    "DEVELOPMENT_RECORD_VERSION",
    "ERRATA_RECORD_VERSION",
    "ERRATUM_OPERATION_VALUES",
    "EVIDENCE_ROLE_VALUES",
    "PRIVATE_SOURCE_OBJECT_LOCATOR_VERSION",
    "RIGHTS_STATUS_VALUES",
    "SOURCE_OBJECT_CATALOG_VERSION",
    "SOURCE_OBJECT_HYDRATION_RECEIPT_VERSION",
    "SOURCE_REGISTER_VERSION",
    "TARGET_KIND_VALUES",
    "AccessScope",
    "AdapterResult",
    "AmendmentOperation",
    "AmendmentSet",
    "AstSourceIdentity",
    "DevelopmentDisposition",
    "DevelopmentLineage",
    "DevelopmentRecord",
    "DevelopmentRecordKind",
    "ErratumOperation",
    "ErratumRecord",
    "EvidenceAdapter",
    "EvidenceDiagnostic",
    "EvidenceRole",
    "HydrationStatus",
    "IccActionStage",
    "IccCommitteeActionPdfAdapter",
    "IccCommitteeActionReportPdfAdapter",
    "IccDevelopmentTextAdapter",
    "IccErrataPdfAdapter",
    "IccProposalMonographPdfAdapter",
    "JurisdictionalAmendmentPatch",
    "NormalizedWashingtonWacHtmlAdapter",
    "ObjectProvider",
    "PrivateSourceObjectLocator",
    "PrivateSourceObjectLocatorRegistry",
    "PublicationIdentity",
    "RightsStatus",
    "SourceObjectCatalog",
    "SourceObjectFetcher",
    "SourceObjectHydrationReceipt",
    "SourceObjectRequirement",
    "SourceRegion",
    "SourceRegister",
    "SourceRegisterEntry",
    "TargetKind",
    "WashingtonOfficialWacHtmlAdapter",
    "WashingtonWacHtmlAdapter",
    "amendment_patch_from_dict",
    "development_record_from_dict",
    "erratum_record_from_dict",
    "hydrate_source_object",
    "private_source_object_locator_registry_from_dict",
    "publication_state_id",
    "run_evidence_adapter",
    "source_object_catalog_from_dict",
    "source_register_from_dict",
    "validate_source_object_catalog",
    "validate_source_object_requirement",
    "verify_local_source_object",
]
